### PR TITLE
Updating Express template

### PR DESCRIPTION
**Pull request by lostintangent**
This PR updates the existing Node.js Express template in the following ways:

1. Reducing some clutter in order to make the sample appear simpler when cloning it (e.g. I removed the `typings` folder since VS and VS Code will automatically acquire these when editing)

2. Cleaning up the `package.json` file so as to not mention ex-MS employees, older products (e.g. WebMatrix)

3. Updating the Node.js dependency to 6.9.4, since that is the current LTS branch, and allows the app to make use of a few simple ES6 features (e.g. arrow functions)

4. Updating the Express version and re-factoring the sample code to adapt to API deprecations (e.g. the removal of the `Express.prototype.configure` method)

5. Switching to using the Pug view engine instead of Jade, since this is the replacement. The view code is actually 100% the same, but it helps to make sure the sample uses the latest terminology/library.

6. Adding some simple instructional/next steps comments to the code, to potentially help inform/guide users on how to play around with the app

I tested this using a free-tier App Service plan, and also verified that the other two Node.js templates work when using Node v6.9.4, which this template now depends on.

### CODE REVIEW

**Comment by lostintangent** [comment]
@fashaikh Let me know if there's anything I can help with regarding updating the default Node.js dependency. Also, can you verify whether renaming the zip file will result in the name of the sample being changed in the actual web experience? If not, do I need to change that string somewhere else?

**Comment by fashaikh** [comment]
@lostintangent : We'll need to update ` https://github.com/projectkudu/TryAppService/search?utf8=%E2%9C%93&q=ExpressJS ` .
@brendankowitz : If tryappservice.azure.com/api/templates started returning `Express` instead of `ExpressJS` for this template would the acom frontend care ?

**Comment by brendankowitz** [comment]
Yes, if the template name changes acom won't show it as it won't match the metadata. It would be a simple change to our appservicetemplates.json to update it.

**Comment by lostintangent** [comment]
@fashaikh OK, I just submitted a [PR](https://github.com/projectkudu/TryAppService/pull/72) to address the needed changes in the `TryAppService` repo. Let me know if that looks good.

@brendankowitz I didn't notice that file anywhere, so let me know if I can help with updating it, in addition to this PR and the `TryAppService` one.

**Comment by lostintangent** [comment]
@fashaikh @brendankowitz FYI, just submitted the [ACOM change](https://github.com/Azure/acom/pull/15568). Let me know if this looks right.

I'm assuming that `tryappservice.azure.com/api/templates` needs to be updated to return `Express` instead of `ExpressJs`, but I'm not sure if that's something I need to change or if it will be dynamically picked up from the fact that I renamed the zip in this repo.

**Comment by lostintangent** [comment]
The ACOM change was just deployed to a test instance, and I notice that the `Express` template is no longer displayed, which I assume is because the API returned `ExpressJS`, whereas my ACOM change now expects `Express`: https://acom-15568-merge.azurewebsites.net/en-us/try/app-service/web/.

**Comment by fashaikh** [comment]
Yes. that sounds right.. 
@brendankowitz is it possible to point the auto-deployed sites to `trywebsites-next.azurewebsites.net` instead of `tryappservice.azure.com`  (If it isn't already pointing there) ?  That way we can test it E2E before deploying.

**Pull request merged**
